# -*- coding: utf-8 -*-
"""HRAnalytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTEfWtQ9jgSrF6mlySZa6m0EZpnLZExN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("HR_Analytics.csv")

df

df.head()

df.tail()

df.info()

df.describe().T

df.isnull().any()

df.isnull().sum()/df.shape[0]*100

df_zero = df.fillna(0)
print(df_zero)

df.duplicated().sum

for i in df.columns:
  print(i,df[i].nunique())

def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

plt.figure(figsize=(12, 8))
sns.histplot(df['AgeGroup'], kde='True', bins=30)
plt.title('Age Group Distribution')
plt.xlabel('Age Group')
plt.ylabel('Frequency')
plt.show()

attrition_counts = df['Attrition'].value_counts()

plt.figure(figsize=(12,8))
plt.pie(attrition_counts, labels=attrition_counts.index, autopct='%1.1f%%', startangle=90)
plt.title('Attrition Breakdown')
plt.axis('equal')
plt.show()

attrition_counts = df['Department'].value_counts()

plt.figure(figsize=(12,8))
plt.pie(attrition_counts, labels=attrition_counts.index, autopct='%1.1f%%', startangle=90)
plt.title('Department Breakdown')
plt.axis('equal')
plt.show()

plt.figure(figsize=(16, 10))
sns.countplot(x='EducationField', data=df)
plt.title('Education Field Distribution')
plt.xlabel('Education Fields')
plt.ylabel('Count')
plt.show()

attrition_counts = df['Gender'].value_counts()

plt.figure(figsize=(12,8))
plt.pie(attrition_counts, labels=attrition_counts.index, autopct='%1.1f%%', startangle=90)
plt.title('Gender Breakdown')
plt.axis('equal')
plt.show()

import plotly.express as px

fig = px.scatter_3d(df,
                    x='TotalWorkingYears',
                    y='Age',
                    z='MonthlyIncome',
                    color='Attrition',
                    title='Income vs Experience vs Age by Attrition',
                    opacity=0.7)
fig.show()